manager/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manager/.apex/src/classes/OrderController.cls
public with sharing class OrderController {
	@AuraEnabled
	public static Order__c createOrder(String productName, Integer totalProductCount, Integer totalPrice) {
		Order__c newOrder = new Order__c();
		newOrder.Name = productName;
		newOrder.TotalProductCount__c = totalProductCount;
		newOrder.TotalPrice__c = totalPrice;

		// Сохранить новый заказ
		insert newOrder;

		// Возвратить созданный заказ
		return newOrder;
	}
}