manager/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manager/.apex/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manager/src/classes/OrderTriggerTest.cls
@isTest
public class OrderTriggerTest {
	@isTest
	static void testOrderTrigger() {
		// Создаем тестовый заказ
		Order__c testOrder = new Order__c(Name = 'Test Order');
		insert testOrder;

		// Создаем тестовые позиции заказа
		OrderItem__c item1 = new OrderItem__c(OrderId__c = testOrder.Id, Quantity__c = 2, Price__c = 10);
		OrderItem__c item2 = new OrderItem__c(OrderId__c = testOrder.Id, Quantity__c = 3, Price__c = 20);
		insert new List<OrderItem__c> { item1, item2 };

		// Обновляем заказ, чтобы триггер сработал
		update testOrder;

		// Обновляем данные заказа из базы данных
		testOrder = [SELECT TotalProductCount__c, TotalPrice__c FROM Order__c WHERE Id = :testOrder.Id];

		// Проверяем, что триггер правильно посчитал количество продуктов и общую цену
		System.assertEquals(5, testOrder.TotalProductCount__c);
		System.assertEquals(80, testOrder.TotalPrice__c);
	}
}