manager/src/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manager/.apex/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manager/.apex/src/classes/OrderItemTriggerHandler.cls
public with sharing class OrderItemTriggerHandler {
	@AuraEnabled
	public static void createOrderWithItems(List<Id> productIds, List<Integer> quantities, List<Decimal> prices) {
		// Проверка на null
		if (productIds == null || quantities == null || prices == null ||
				productIds.isEmpty() || quantities.isEmpty() || prices.isEmpty()) {
			throw new IllegalArgumentException('Некоторые параметры не заполнены или пусты.');
		}

		System.debug('Содержимое корзины: ' + productIds + ', ' + quantities + ', ' + prices);

		// Создание заказа
		Order__c newOrder = new Order__c();
		newOrder.Name = 'Заказ ' + Datetime.now().format('yyyyMMddHHmmss');
		insert newOrder;
		System.debug('Создан новый заказ: ' + newOrder.Id);

		// Создание элементов заказа
		List<OrderItem__c> orderItems = new List<OrderItem__c>();
		for (Integer i = 0; i < productIds.size(); i++) {
			OrderItem__c orderItem = new OrderItem__c();
			orderItem.OrderId__c = newOrder.Id;
			orderItem.ProductId__c = productIds[i];
			orderItem.Quantity__c = quantities[i];
			orderItem.Price__c = quantities[i] * prices[i];
			orderItems.add(orderItem);
		}
		insert orderItems;
		System.debug('Созданы элементы заказа: ' + orderItems);

		// Обновление заказа с общими значениями
		update newOrder;
		System.debug('Заказ обновлен: ' + newOrder);
	}
}