manager/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manager/.apex/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manager/.apex/src/classes/OrderHelper.cls
public class OrderHelper {
	public static void updateOrderTotals(Set<Id> orderIds) {
		List<Order__c> ordersToUpdate = new List<Order__c>();

		for (Id orderId : orderIds) {
			Order__c order = [SELECT Id, (SELECT Quantity__c, Price__c FROM OrderItems__r) FROM Order__c WHERE Id = :orderId];

			Decimal totalProductCount = 0;
			Decimal totalPrice = 0;

			for (OrderItem__c item : order.OrderItems__r) {
				totalProductCount += item.Quantity__c;
				totalPrice += item.Price__c * item.Quantity__c;
			}

			Order__c orderUpdate = new Order__c(Id = orderId);
			orderUpdate.TotalProductCount__c = totalProductCount;
			orderUpdate.TotalPrice__c = totalPrice;

			ordersToUpdate.add(orderUpdate);
		}

		update ordersToUpdate;
	}
}