manager/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manager/.apex/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manager/.apex/src/classes/OrderTriggerHandler.cls
public with sharing class OrderTriggerHandler {
	public static void calculateTotalValues(List<Order__c> orders) {
		for (Order__c order : orders) {
			// Initialize total product count and total price
			Decimal totalProductCount = 0;
			Decimal totalPrice = 0;

			// Query related Order Items using the child relationship name
			List<OrderItem__c> orderItems = [SELECT Quantity__c, Price__c FROM OrderItem__c WHERE OrderId__c = :order.Id];

			// Calculate total product count and total price
			for (OrderItem__c item : orderItems) {
				totalProductCount += item.Quantity__c;
				totalPrice += item.Quantity__c * item.Price__c;
			}

			// Set the calculated values to the order
			order.TotalProductCount__c = totalProductCount;
			order.TotalPrice__c = totalPrice;
		}
	}
}