manager/src/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manager/.apex/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manager/src/classes/OrderController.cls
public class OrderController {
	@AuraEnabled
	public static void recalculateOrderTotals(Id orderId) {
		// Запрашиваем заказ и связанные с ним элементы заказа
		Order__c order = [SELECT Id, (SELECT Id FROM OrderItems__r) FROM Order__c WHERE Id = :orderId LIMIT 1];

		// Запрашиваем все связанные OrderItem__c
		List<OrderItem__c> orderItems = [SELECT Id FROM OrderItem__c WHERE Order__c = :orderId];

		// Обновляем все OrderItem__c
		if (!orderItems.isEmpty()) {
			update orderItems;
		}

		// Обновляем заказ, чтобы триггер пересчитал значения
		update order;
	}
}