manager/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manager/.apex/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manager/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manager/src/classes/OrderControllerTest.cls
@isTest
public class OrderControllerTest {

	@testSetup
	static void setup() {
		List<Product__c> products = new List<Product__c>();
		for (Integer i = 0; i < 3; i++) {
			products.add(new Product__c(
					Name = 'Product ' + i,
					Price__c = 100 + i
			));
		}
		insert products;
	}

	@isTest
	static void testSaveOrder() {
		List<Product__c> products = [SELECT Id, Price__c FROM Product__c LIMIT 3];
		List<Id> productIds = new List<Id>();
		List<Decimal> prices = new List<Decimal>();

		for (Product__c product : products) {
			productIds.add(product.Id);
			prices.add(product.Price__c);
		}

		Test.startTest();
		OrderController.saveOrder(productIds, prices);
		Test.stopTest();

		Order__c newOrder = [SELECT Id, Name, AccountId__c, TotalProductCount__c, TotalPrice__c FROM Order__c LIMIT 1];
		System.assertNotEquals(null, newOrder, 'Order should not be null');
		System.assertEquals('New Order', newOrder.Name, 'Order Name should be "New Order"');
		System.assertEquals(UserInfo.getUserId(), newOrder.AccountId__c, 'Order AccountId should match the current user ID');
		System.assertEquals(3, newOrder.TotalProductCount__c, 'TotalProductCount should be 3');
		System.assertEquals(300, newOrder.TotalPrice__c, 'TotalPrice should be the sum of product prices');

		List<OrderItem__c> orderItems = [SELECT Id, OrderId__c, ProductId__c, Quantity__c, Price__c FROM OrderItem__c WHERE OrderId__c = :newOrder.Id];
		System.assertEquals(3, orderItems.size(), 'There should be 3 order items');
		for (Integer i = 0; i < orderItems.size(); i++) {
			System.assertEquals(newOrder.Id, orderItems[i].OrderId__c, 'OrderItem OrderId should match the new order ID');
			System.assertEquals(productIds[i], orderItems[i].ProductId__c, 'OrderItem ProductId should match the product ID');
			System.assertEquals(1, orderItems[i].Quantity__c, 'OrderItem Quantity should be 1');
			System.assertEquals(prices[i], orderItems[i].Price__c, 'OrderItem Price should match the product price');
		}
	}

	@isTest
	static void testSaveOrderWithMismatchedLists() {
		List<Id> productIds = new List<Id>{'001000000000001', '001000000000002'};
		List<Decimal> prices = new List<Decimal>{100};

		try {
			Test.startTest();
			OrderController.saveOrder(productIds, prices);
			Test.stopTest();
			System.assert(false, 'Expected IllegalArgumentException was not thrown');
		} catch (IllegalArgumentException e) {
			System.assertEquals('Product IDs and prices lists must have the same size', e.getMessage(), 'Exception message should match');
		}
	}
}