manager/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>first Example</fullName>
                    <default>true</default>
                    <label>first Example</label>
                </value>
                <value>
                    <fullName>second Example</fullName>
                </value>
                <value>
                    <fullName>third Example</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <description>link to image</description>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>first Example</fullName>
                    <default>true</default>
                    <label>first Example</label>
                </value>
                <value>
                    <fullName>second Example</fullName>
                </value>
                <value>
                    <fullName>third Example</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manager/.apex/src/classes/ProductController.cls
public with sharing class ProductController {
	@AuraEnabled(cacheable=true)
	public static List<Product__c> getAllProducts() {
		return [SELECT Id, Name, Description__c, Type__c, Family__c, Price__c, Image__c FROM Product__c];
	}

	@AuraEnabled
	public static void saveProduct(String name, String description, String type, String family, String image, Decimal price) {
		try {
			List<String> validTypes = new List<String>{'first Example', 'second Example', 'third Example'};
			List<String> validFamilies = new List<String>{'first Example', 'second Example', 'third Example'};

			if (!validTypes.contains(type)) {
				throw new AuraHandledException('Некорректное значение для типа.');
			}

			if (!validFamilies.contains(family)) {
				throw new AuraHandledException('Некорректное значение для семейства.');
			}

			Product__c product = new Product__c(
					Name = name,
					Name__c = name,
					Description__c = description,
					Type__c = type,
					Family__c = family,
					Image__c = image,
					Price__c = price
			);
			insert product;
		} catch (Exception e) {
			System.debug('Exception: ' + e.getMessage());
			throw new AuraHandledException('Ошибка при сохранении продукта: ' + e.getMessage());
		}
	}
}