manager/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>first Example</fullName>
                    <default>true</default>
                    <label>first Example</label>
                </value>
                <value>
                    <fullName>second Example</fullName>
                </value>
                <value>
                    <fullName>third Example</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

manager/src/classes/ProductFilterController.cls
public with sharing class ProductFilterController {

	@AuraEnabled(cacheable=true)
	public static List<Product__c> getFilteredProducts(String typeFilter, String filterFilter) {
		String query = 'SELECT Id, Name, Type__c, Filter__c FROM Product__c WHERE ';

		if (typeFilter != null) {
			query += 'Type__c = \'' + String.escapeSingleQuotes(typeFilter) + '\'';
		}

		if (filterFilter != null) {
			if (typeFilter != null) {
				query += ' AND ';
			}
			query += 'Filter__c = \'' + String.escapeSingleQuotes(filterFilter) + '\'';
		}

		return Database.query(query);
	}

}